name: Gradle Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # https://github.com/marketplace/actions/checkout
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Build with Gradle
      run: ./gradlew build
