name: Release Publish

on: [push]

jobs:
  shared-outputs:
    name: Shared Outputs
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.modified_tag.outputs.version }}
    steps:
      - id: modified_tag
        name: Modify Tag
        run: |
          tag_name="${{ github.event.release.tag_name }}"
          version=$(echo "$tag_name" | sed "s/v//")
          echo "::set-output name=version::$version"
  release:
    runs-on: ubuntu-latest
    needs: shared-outputs
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Build with Gradle
      run: ./gradlew publish
      env:
        # https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle#publishing-packages-to-github-packages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_VERSION: ${{ needs.shared-outputs.outputs.version }}

